### ISSUE TITLE
Payloads should be of type param

### ISSUE THREAD

**Issue by nsoblath** [project8/dripline-cpp#3]
This would conform to the dripline standard that payloads can have "any" type.

From the perspective of creating messages, this should be fine.

The ability to do this from the perspective of encoding/decoding AMQP messages needs to be studied.

**Comment by laroque** [comment]
Is the idea here just that currently it is typed as a `param_node`, but in `message` it should be `param`, and only specialize to `param_node` for cases where that is called for? (and related, received messages should support decoding to a `param`, which may or may not be a `param_node`?

**Comment by nsoblath** [comment]
Yes, that's the general idea.  And yes, that's right.

**Comment by nsoblath** [comment]
Done in driplineorg
