### ISSUE TITLE
message::f_rks should be removed if it's not used

### ISSUE THREAD

**Issue by nsoblath** [project8/dripline-cpp#6]

**Comment by laroque** [comment]
I assume this is supposed to be `message::f_rks`. I just did a grep on whatever old version of psyllid was on my older laptop and found only use of `parsed_rks` except in the batch executor (which is what I was working on when I asked the question prompting this issue). I think we can remove it it, I can probably check that in psyllid later this week.

**Comment by nsoblath** [comment]
Yeah, `message::f_rks`.  I find no use of it in current psyllid.

**Comment by laroque** [comment]
Started to do this, but some questions come up:

>it is going to leave us with `bool set_routing_key_specifier( const routing_key_specifier& a_parsed_rks) { f_parsed_rks=a_parsed_rks}` … which i don’t really like
seems like the method should be renamed, and/or use `mv_accessible`
and if there’s no f_rks, maybe we don’t need to call it parsed?

... pausing on this until we do the audit of consistency with dripline-python behavior to decide what "expected" should look like

**Comment by nsoblath** [comment]
Outdated
